name: cmake build and mcp patch

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'  # 每天自动更新

jobs:
  update-patch:
    runs-on: windows-latest
    steps:

      - name: Checkout current repository
        uses: actions/checkout@v4

      #      todo move into mcp rep

      #      - name: Setup Go environment
      #        uses: actions/setup-go@v5
      #        with:
      #          go-version: '1.25.0-rc.1'
      #          check-latest: true

      # 5. 运行bindgen测试（禁用CGO） - 保留注释用于后续启用
      #      - name: Run bindgen tests
      #        shell: bash
      #        run: |
      #          cd HyperDbg/hyperdbg/libhyperdbg/code/export
      #          CGO_ENABLED=0 go test . -v

      - name: Install Windows Driver Kit (WDK)
        run: |
          $wdkSetupPath = "$Env:TEMP\wdksetup.exe"
          (New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=2196230', $wdkSetupPath)
          Start-Process -FilePath $wdkSetupPath -ArgumentList "/quiet" -NoNewWindow -Wait
        shell: powershell

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build HyperDbg with cmake
        shell: cmd
        run: |
          ::git clone --progress https://github.com/ddkwork/keystone.git
          ::rmdir /s /q cmake-build-release
          git submodule update --init --recursive --remote
          set "DIA_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK"
          cmake -G "Visual Studio 17 2022" -A x64 -S . -B cmake-build-release -DDIA_SDK_INCLUDE_DIR="%DIA_PATH%\include"
          cmake --build cmake-build-release --config Release --parallel 6
        working-directory: hyperdbg

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hyperdbg-binaries
          path: hyperdbg/cmake-build-release/debugger_server
          if-no-files-found: warn
          retention-days: 1

